sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        pales/h5/NyOXUnoHm6PUk+XZ6zeHWEQUPyApJlOMthF9chHSLzFJT1SXdZjBQ037VDkkcsOoTOwpBQtYNVsamMV0b3CFsv5bQVst6BCTmSwusfHbE1I+xop7W6cCMQWmqKaPjdRJgrOuzE6Ui/ltxVHa2Nzd1pF64F61REhskUE7co2OcH3s9hQ9a55DdPgLufCUkcExKTm3ZBFR1UZeRoI54RAQ50zvQI+rCUnzhImiFjnyUUF+X9PPenXi+gdx9dxGXSZaDEELd3MWxmwal2KCYRS8imnbsgtjr0Ko207gxv1dPAybkqs/C42CU6E5AFpg1dtZno8NsvU3ePh1mRkEldOgbC/ONMRTtjcmvisDYKM6jGnri0yww1QYkRLr1k5lcXcwu/on4zPFk6p1MaOlu7eL6mSyeAieo+GVBKFxFYmoPG7vgsSStmQZGwlE1lCeUJZQ0g2xQIvXAHLPDGmPe3bRKOWRuVO5/wn2IKBKk87MSRKKFROHpot+vH/J/4gwjQ9OkdIrK0kABnoXBnFR2HaVfCQKCZI5EfZA3/j/COisr3bpUg9OociKisBljEGBONOQJCMJEE5OARVirt5avXt7sBGuOZh4Arp0MoBwvPBjZopUzFUwKNAHCa5NAf2wZ+N2F1nr/BlhKgkU5p/unG1kKDQ1agaYgCf0xw=
    - secure: >-
        fLxx1/JLeSSeGvaWFl+WY0ld4Bjrc/hPw+Z0/wiC7RMLIPadrX6Iv6GPeASoPhHxO9jyyKg6iSj0yD4C25dLdACQTf7TYpGnsryLTi3LPpP6huxa1Y3Db3aLtDtQALRR5QCTPnrjKVVDlVzVK8JFlP+Vk7KxBnKG1s7A7AAOaubmFcwmiB2/KfHEyAtei3BAKPdWTcQy/8+m6tixOUDUhDeFzAaHUKQtlbSIh+P2IgDZO74BJdadTD3w3kYo8CxrWJeJyz9rZxI50Gv2uU9kJvqGZRS1PC3aKigSNKnv++2Skl31W1VfrV1S4KrHPjquDvRne0cDRN96rrmmT0gTaiIZwh8q166O8/sl1KrcsxpHz2CyeJPzGPxNEBWc6Q2tRG1e462ac6+RNhCCRmolYAwo6+9fL9xXTLnG04DeC7s6h8dEAkii4cUygz+uqo/8FeoOJu0lUGbiEzCWuCD5CmokD6ubayBGgB9XlFcHn6lZOcafIvLj1OCsoKcsr9au0tS8fiX/zu+vpnIqP4Ql2VqP98sUzFfx4kN1XSkAPIhvaWsfSC6fTOfPrQy0zZgwFV2so0c6BR7FG+8zoYlGXK+yo8yYdt9K7N7Mz8oT24TdRdp8BuXq4K9O00Vr9XEA2/5geVx0MS44z4MRwKaA3JidpcCqFWP19WC8Vy+OYVI=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
